server:
  port:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LeahFu5149918186
    url: jdbc:mysql://localhost:3306/Smart_Campus_Management_System?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    hikari:
      minimum-idle: 10 # Minimum number of idle connections
      maximum-pool-size: 10 # The maximum number of connections, the default is 10
      idle-timeout: 120000 # The maximum time an idle connection can survive
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000 # The maximum time that a database connection can survive
      connection-test-query: Select 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.qq.com
    port: 465
    username: 379533177@qq.com
    password: ryjxbuztvacacahj
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

# User avatar storage path
user:
  icon: /Users/leahfu/Documents/Smart_Campus_Management/
